export const LOGIN = "LOGIN"
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER = "REGISTER"
export const REGISTER_START = "REGISTER_START"
export const REGISTER_SENT = "REGISTER_SENT"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const VERIFY_START = "VERIFY_START"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAILURE = "VERIFY_FAILURE"

export const SET_LANG_ENG = "SET_LANG_ENG"
export const SET_LANG_SIN = "SET_LANG_SIN"

export const SET_DETAILS = "SET_DETAILS"
export const SET_EVIDENCE = "SET_EVIDENCE"
export const SUBMIT_CLAIM_START = "SUBMIT_CLAIM_START"
export const SUBMIT_CLAIM_SUCCESS = "SUBMIT_CLAIM_SUCCESS"
export const SUBMIT_CLAIM_FAILURE = "SUBMIT_CLAIM_ERROR"


export const SET_CLAIM_ID = "SET_CLAIM_ID"
export const APPROVE_CLAIM_SUCCESS = "APPROVE_CLAIM_SUCCESS"
export const APPROVE_CLAIM_FAIL = "APPROVE_CLAIM_FAIL"
export const REJECT_CLAIM_SUCCESS = "REJECT_CLAIM_SUCCESS"
export const REJECT_CLAIM_FAIL = "REJECT_CLAIM_FAIL"


