export const LOGIN = "LOGIN"
export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const REGISTER = "REGISTER"
export const REGISTER_START = "REGISTER_START"
export const REGISTER_SENT = "REGISTER_SENT"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const VERIFY_START = "VERIFY_START"
export const VERIFY_SUCCESS = "VERIFY_SUCCESS"
export const VERIFY_FAILURE = "VERIFY_FAILURE"

export const SET_LANG_ENG = "SET_LANG_ENG"
export const SET_LANG_SIN = "SET_LANG_SIN"